FROM ubuntu:trusty
COPY ["loop.sh", "/"]
#copia el archivo loop.sh a la carpeta /
#CMD /loop.sh
#ejecuta el archivo loop.sh  Ejecuta el proceso como hijo del shell
CMD ["/loop.sh"]
#Exec: Ejecuta el comando como principal, siempre tratar de usar el formato exec
