FROM ubuntu:trusty
ENTRYPOINT [ "/bin/ping", "-c", "3" ]
#comando por defecto que se va a correr
CMD ["localhost"]
#llama al binario ping para enviar un paque te a otro destino y esperar la respuesta
#hacer 3 veces ping a localhost(contenedor)

